<?php
// $Id$

/**
 *  @file
 *  NYSS Search
 *
 *  This module modifies Drupal search to search for content only authored by Senator.
 */

/**
 *  Implements hook_menu().
 */

/*
function nyss_search_db_rewrite_sql($query, $primary_table, $primary_field, $args) {
  if ($query == '' && $primary_table == 'n' && $primary_field == 'nid' && empty($args)) {
    $senator = nyss_senator();
    print 'hello!<pre>' . print_r($_SESSION['blah'], true) . '</pre>grr<br /><br />';
    return array('join' => "LEFT JOIN {content_field_senator} AS cfs ON cfs.nid = n.nid", 'where' => " cfs.field_senator_nid  IN ('95') ");
  }
}
*/

/**
 * Implementation of hook_block().
 */
function nyss_search_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('NYSS Search form');
    // Not worth caching.
    $blocks[0]['cache'] = BLOCK_NO_CACHE;
    return $blocks;
  }
  else if ($op == 'view' && user_access('search content')) {
    $block['content'] = drupal_get_form('nyss_search_block_form');
    return $block;
  }
}
function nyss_search_forms() {
  $forms['nyss_search_block_form']= array(
    'callback' => 'nyss_search_box',
    'callback arguments' => array('nyss_search_block_form'),
  );
  return $forms;
}

function nyss_search_box(&$form_state, $form_id) {
  $form[$form_id] = array(
    '#type' => 'textfield',
    '#size' => 15,
    '#default_value' => 'Search',
    '#attributes' => array('title' => t('Enter the terms you wish to search for.'), 'onfocus' => "if (this.value == 'Search') {this.value = '';}", 'onblur' => "if (this.value == '') {this.value = 'Search';}"),
  );

  $senator = nyss_senator();
  $form['sen_nid'] = array('#type' => 'hidden', '#value' => ($senator ? $senator->nid : ''));

  $form['submit'] = array('#type' => 'submit', '#value' => t('Search'));
  $form['#submit'][] = 'nyss_search_box_form_submit';
  $form['#validate'][] = 'search_box_form_validate';

  return $form;
}
function nyss_search_box_form_submit($form, &$form_state) {
  $form_id = $form['form_id']['#value'];

  $_SESSION['sen_nid'] = $form['sen_nid']['#post']['sen_nid'];

  $form_state['redirect'] = 'search/nyss_search/'. trim($form_state['values'][$form_id]);
}

/**
 * Implementation of hook_search().
 */
function nyss_search_search($op = 'search', $keys = null) {
  switch ($op) {
    case 'name':
      return t('Senator Content');

    case 'search':
      // Build matching conditions
      list($join1, $where1) = _db_rewrite_sql();

      $arguments1 = array();
      $conditions1 = 'n.status = 1';

      if ($type = search_query_extract($keys, 'type')) {
        $types = array();
        foreach (explode(',', $type) as $t) {
          $types[] = "n.type = '%s'";
          $arguments1[] = $t;
        }
        $conditions1 .= ' AND ('. implode(' OR ', $types) .')';
        $keys = search_query_insert($keys, 'type');
      }

      if ($category = search_query_extract($keys, 'category')) {
        $categories = array();
        foreach (explode(',', $category) as $c) {
          $categories[] = "tn.tid = %d";
          $arguments1[] = $c;
        }
        $conditions1 .= ' AND ('. implode(' OR ', $categories) .')';
        $join1 .= ' INNER JOIN {term_node} tn ON n.vid = tn.vid';
        $keys = search_query_insert($keys, 'category');
      }

      if ($_SESSION['sen_nid'] != '') {
        $join1 .= ' LEFT JOIN {content_field_senator} cfs ON cfs.nid = n.nid';
        if ($where1 != '') {
          $where1 .= ' AND';
        }
        $where1 .= ' cfs.field_senator_nid = ' . $_SESSION['sen_nid'];
      }

      // Build ranking expression (we try to map each parameter to a
      // uniform distribution in the range 0..1).
      $ranking = array();
      $arguments2 = array();
      $join2 = '';
      // Used to avoid joining on node_comment_statistics twice
      $stats_join = FALSE;
      $total = 0;
      if ($weight = (int)variable_get('node_rank_relevance', 5)) {
        // Average relevance values hover around 0.15
        $ranking[] = '%d * i.relevance';
        $arguments2[] = $weight;
        $total += $weight;
      }
      if ($weight = (int)variable_get('node_rank_recent', 5)) {
        // Exponential decay with half-life of 6 months, starting at last indexed node
        $ranking[] = '%d * POW(2, (GREATEST(MAX(n.created), MAX(n.changed), MAX(c.last_comment_timestamp)) - %d) * 6.43e-8)';
        $arguments2[] = $weight;
        $arguments2[] = (int)variable_get('node_cron_last', 0);
        $join2 .= ' LEFT JOIN {node_comment_statistics} c ON c.nid = i.sid';
        $stats_join = TRUE;
        $total += $weight;
      }
      if (module_exists('comment') && $weight = (int)variable_get('node_rank_comments', 5)) {
        // Inverse law that maps the highest reply count on the site to 1 and 0 to 0.
        $scale = variable_get('node_cron_comments_scale', 0.0);
        $ranking[] = '%d * (2.0 - 2.0 / (1.0 + MAX(c.comment_count) * %f))';
        $arguments2[] = $weight;
        $arguments2[] = $scale;
        if (!$stats_join) {
          $join2 .= ' LEFT JOIN {node_comment_statistics} c ON c.nid = i.sid';
        }
        $total += $weight;
      }
      if (module_exists('statistics') && variable_get('statistics_count_content_views', 0) &&
          $weight = (int)variable_get('node_rank_views', 5)) {
        // Inverse law that maps the highest view count on the site to 1 and 0 to 0.
        $scale = variable_get('node_cron_views_scale', 0.0);
        $ranking[] = '%d * (2.0 - 2.0 / (1.0 + MAX(nc.totalcount) * %f))';
        $arguments2[] = $weight;
        $arguments2[] = $scale;
        $join2 .= ' LEFT JOIN {node_counter} nc ON nc.nid = i.sid';
        $total += $weight;
      }

      // When all search factors are disabled (ie they have a weight of zero),
      // the default score is based only on keyword relevance and there is no need to
      // adjust the score of each item.
      if ($total == 0) {
        $select2 = 'i.relevance AS score';
        $total = 1;
      }
      else {
        $select2 = implode(' + ', $ranking) . ' AS score';
      }

      // Do search.
      $find = do_search($keys, 'node', 'INNER JOIN {node} n ON n.nid = i.sid '. $join1, $conditions1 . (empty($where1) ? '' : ' AND '. $where1), $arguments1, $select2, $join2, $arguments2);

      // Load results.
      $results = array();
      foreach ($find as $item) {
        // Build the node body.
        $node = node_load($item->sid);
        $node->build_mode = NODE_BUILD_SEARCH_RESULT;
        $node = node_build_content($node, FALSE, FALSE);
        $node->body = drupal_render($node->content);

        // Fetch comments for snippet.
        $node->body .= module_invoke('comment', 'nodeapi', $node, 'update index');
        // Fetch terms for snippet.
        $node->body .= module_invoke('taxonomy', 'nodeapi', $node, 'update index');

        $extra = node_invoke_nodeapi($node, 'search result');
        $results[] = array(
          'link' => url('node/'. $item->sid, array('absolute' => TRUE)),
          'type' => check_plain(node_get_types('name', $node)),
          'title' => $node->title,
          'user' => theme('username', $node),
          'date' => $node->changed,
          'node' => $node,
          'extra' => $extra,
          'score' => $item->score / $total,
          'snippet' => search_excerpt($keys, $node->body),
        );
      }
      return $results;
  }
}

/**
 * Implements hook_searchtext_alter.
 * This 
 *  @param $text
 *    the search text to be indexed
 */
function nyss_search_searchtext_alter(&$alter_values) {
  if ($alter_values['type'] == 'node') {
    $node = node_load($alter_values['sid']);
    $flag = flag_get_flag('exclude_from_search') or die('no "exclude_from_search" flag defined');
    if ($flag->is_flagged($alter_values['sid'])) {
      $alter_values['text'] = '';
    }
  }
}
