<?php
// $Id$

/**
 *  @file
 *  Formats a number as an ordinal.
 */

/**
 *  This function will add the correct ordinal suffix to any number.
 *  1st, 2nd, 3rd, 4th, etc...
 *
 *  Original function written by Marcus L. Griswold (vujsa)
 *  Can be found at http://www.handyphp.com
 *
 *  @param $value
 *    A number.
 *  @param $sup
 *    (optional) If TRUE, then format the ordinal suffix as a superscript.
 *  @return
 *    A string composed of the original value with the ordinal suffix.
 */
function ordinal($value, $sup = FALSE) {
    if (substr($value, -2, 2) == 11 || substr($value, -2, 2) == 12 || substr($value, -2, 2) == 13) {
        $suffix = "th";
    }
    else if (substr($value, -1, 1) == 1) {
        $suffix = "st";
    }
    else if (substr($value, -1, 1) == 2) {
        $suffix = "nd";
    }
    else if (substr($value, -1, 1) == 3) {
        $suffix = "rd";
    }
    else {
        $suffix = "th";
    }
    if($sup) {
        $suffix = "<sup>". $suffix ."</sup>";
    }
    return $value . $suffix;
}
